
실습 과제1: NumPy를 활용한 행렬 변형 실습
문제 1: 난수 행렬 생성
N = 6과 M = 5로 설정하고, 0과 1 사이의 난수를 사용하여 (N, M) 형태의 행렬 A를 생성하세요.
힌트: np.random.rand() 함수를 사용하세요.

문제 2: 새로운 축 추가
행렬 A에 np.newaxis를 사용하여 새로운 축을 추가하고, 결과를 B에 저장하세요. B의 형태는 (N, 1, M)이 되어야 합니다.

문제 3: 슬라이싱을 이용한 특정 요소 변경
행렬 B에서 세 번째 행의 모든 열을 슬라이싱하여 값을 0.3으로 변경하세요.

문제 4: 축 위치를 다르게 설정하여 새로운 행렬 생성
np.newaxis를 사용하여 A의 형태를 (1, N, M)로 변형한 결과를 C에 저장하고, (N, M, 1)로 변형한 결과를 D에 저장하세요. 각 행렬의 형태를 출력하여 확인하세요.

문제 5: 슬라이싱을 통해 부분 행렬 변경
행렬 D에서 마지막 세 행의 모든 요소를 0.8로 변경하세요.



In [2]:
import numpy as np

In [38]:
A= np.random.rand(6,5)
A

array([[0.96444762, 0.8247326 , 0.44802291, 0.18466741, 0.62093922],
       [0.51539587, 0.11715439, 0.16075223, 0.1210439 , 0.14923068],
       [0.69696831, 0.467208  , 0.96726366, 0.68642987, 0.00413675],
       [0.16431693, 0.56338887, 0.67202296, 0.9325531 , 0.42774454],
       [0.47782955, 0.43150594, 0.49570288, 0.53879439, 0.84672185],
       [0.23245161, 0.33223759, 0.47200784, 0.72947017, 0.79531011]])

In [27]:
B = A[:,np.newaxis,:] 
B

array([[[0.68933852, 0.66690616, 0.31518721, 0.51814181, 0.12167972]],

       [[0.67177251, 0.99849475, 0.48691873, 0.69531513, 0.39084295]],

       [[0.35759426, 0.29386995, 0.57944456, 0.21089947, 0.98796577]],

       [[0.58504605, 0.73062804, 0.34594464, 0.55752129, 0.20477843]],

       [[0.72963476, 0.27539544, 0.7946758 , 0.63062515, 0.87196083]],

       [[0.23135394, 0.00963962, 0.86440817, 0.52607642, 0.90403597]]])

In [28]:
B[2:3:,0] = 0.3
B

array([[[0.68933852, 0.66690616, 0.31518721, 0.51814181, 0.12167972]],

       [[0.67177251, 0.99849475, 0.48691873, 0.69531513, 0.39084295]],

       [[0.3       , 0.3       , 0.3       , 0.3       , 0.3       ]],

       [[0.58504605, 0.73062804, 0.34594464, 0.55752129, 0.20477843]],

       [[0.72963476, 0.27539544, 0.7946758 , 0.63062515, 0.87196083]],

       [[0.23135394, 0.00963962, 0.86440817, 0.52607642, 0.90403597]]])

In [29]:
A

array([[0.68933852, 0.66690616, 0.31518721, 0.51814181, 0.12167972],
       [0.67177251, 0.99849475, 0.48691873, 0.69531513, 0.39084295],
       [0.3       , 0.3       , 0.3       , 0.3       , 0.3       ],
       [0.58504605, 0.73062804, 0.34594464, 0.55752129, 0.20477843],
       [0.72963476, 0.27539544, 0.7946758 , 0.63062515, 0.87196083],
       [0.23135394, 0.00963962, 0.86440817, 0.52607642, 0.90403597]])

In [39]:
C= A[np.newaxis,:,:]
D= A[:,:,np.newaxis]

C

array([[[0.96444762, 0.8247326 , 0.44802291, 0.18466741, 0.62093922],
        [0.51539587, 0.11715439, 0.16075223, 0.1210439 , 0.14923068],
        [0.69696831, 0.467208  , 0.96726366, 0.68642987, 0.00413675],
        [0.16431693, 0.56338887, 0.67202296, 0.9325531 , 0.42774454],
        [0.47782955, 0.43150594, 0.49570288, 0.53879439, 0.84672185],
        [0.23245161, 0.33223759, 0.47200784, 0.72947017, 0.79531011]]])

In [40]:
D

array([[[0.96444762],
        [0.8247326 ],
        [0.44802291],
        [0.18466741],
        [0.62093922]],

       [[0.51539587],
        [0.11715439],
        [0.16075223],
        [0.1210439 ],
        [0.14923068]],

       [[0.69696831],
        [0.467208  ],
        [0.96726366],
        [0.68642987],
        [0.00413675]],

       [[0.16431693],
        [0.56338887],
        [0.67202296],
        [0.9325531 ],
        [0.42774454]],

       [[0.47782955],
        [0.43150594],
        [0.49570288],
        [0.53879439],
        [0.84672185]],

       [[0.23245161],
        [0.33223759],
        [0.47200784],
        [0.72947017],
        [0.79531011]]])

In [43]:
D[-3:,:,:]=0.8
D


array([[[0.96444762],
        [0.8247326 ],
        [0.44802291],
        [0.18466741],
        [0.62093922]],

       [[0.51539587],
        [0.11715439],
        [0.16075223],
        [0.1210439 ],
        [0.14923068]],

       [[0.69696831],
        [0.467208  ],
        [0.96726366],
        [0.68642987],
        [0.00413675]],

       [[0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ]],

       [[0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ]],

       [[0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ]]])